stages:
  get_data:
    cmd: python scripts/random_data.py
    deps:
    - scripts/random_data.py
    - trigger.txt 

  process_data:
    cmd: python scripts/preprocess_data.py
    deps:
    - scripts/preprocess_data.py
    - data/raw/sensor_data.csv

  
  train_model:
    cmd: python scripts/train_model.py data/processed/train/train.csv data/processed/test/test.csv model/random_forest_model.joblib
    deps:
      - scripts/train_model.py
      - data/processed/train.csv
      - data/processed/test.csv

    
