stages:
  get_data:
    cmd: python scripts/random_data.py
    deps:
    - scripts/random_data.py
    - trigger.txt 

  process_data:
    cmd: python scripts/preprocess_data.py
    deps:
    - scripts/preprocess_data.py
    - data/raw/sensor_data.csv

    