stages:
  get_data:
    cmd: python scripts/random_data.py
    deps:
    - scripts/random_data.py
    - trigger.txt
    
    # outs:
    # - data/raw/sensor_data.csv
  process_data:
    cmd: python scripts/preprocess_data.py
    deps:
    - scripts/preprocess_data.py
    - data/raw/sensor_data.csv
  
  triggers:
    cmd: date +"%Y-%m-%d %H:%M:%S" > trigger.txt

    # outs:
    # - data/processed/train/train.csv
    # - data/processed/test/test.csv

  # train:
  #   cmd: python train.py
  #   deps:
  #   - train.py
  #   - data_processed.csv
  #   outs:
  #   - by_region.png
  #   metrics:
  #   - metrics.json:
  #       cache: false