name: Generate and preprocess the data

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install DVC
        run: |
          pip install dvc
          dvc remote modify myremote gdrive://1FKchucezQ1fGfWI0Lbu2MtMBeBRaeKJb
          dvc remote modify myremote gdrive_use_service_account true
          dvc remote modify myremote --local \
            gdrive_service_account_json_file_path mlops-secret.json
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run dvc repro
        run: |
          dvc repro
      - name: Push data to DVC remote
        run: |
          dvc push -r myremote
