name: Generate and preprocess the data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install DVC
        run: |
          pip install dvc
          dvc remote modify myremote gdrive_use_service_account true
          dvc remote modify myremote --local \
            gdrive_service_account_json_file_path mlops-secret.json
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Download the data from DVC remote
        run: |
          dvc pull

      - name: Trigger
        run: |
          date > trigger.txt

      - name: Run dvc repro
        run: |
          dvc repro

      - name: DVC Add
        run: |
          dvc add data/raw/sensor_data.csv data/processed/train/train.csv data/processed/test/test.csv
        
      - name: Push data to DVC remote
        run: |
          dvc push -r myremote

      - name: print last 100 lines of data
        run: |
          tail -n 100 data/raw/sensor_data.csv

      - name: Configure Git
        run: |
          git config --global user.email "hammadhabib80@gmail.com"
          git config --global user.name "Hammad Habib"
  
      - name: Add, commit and push the changes
        run: |
          git pull origin main
          git add .
          git commit -m "Update data"
          git push origin main







          