name: Generate and preprocess the data

on:
  push:
    branches:
      - main
  # schedule:
    # - cron: '*/10 * * * *' # Runs every 10 minutes
    # - cron: '0 */3 * * *'  # Runs every 3 hours
    # - cron: '0 0 * * *'  # Runs every day at midnight (00:00)
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install DVC
        run: |
          pip install dvc
          dvc remote modify myremote gdrive_use_service_account true
          dvc remote modify myremote --local \
            gdrive_service_account_json_file_path mlops-secret.json
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Download the data from DVC remote
        run: |
          dvc pull

      - name: Trigger
        run: |
          date > trigger.txt

      - name: print last 100 training data
        run: |
          tail -n 100 data/processed/train/train.csv
      
      - name: print last 100 test of data
        run: |
          tail -n 100 data/processed/test/test.csv

      - name: Run dvc repro
        run: |
          dvc repro

      - name: Print the newly generated data
        run: |
          cat data/processed/new_data.csv
      
      # Deployment Stage
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build the Docker image
        run: docker build -t jawwadhabib/project:latest .
      
      - name: Push the Docker image
        run: docker push jawwadhabib/project:latest
      # ----------------------------------------------
    
      - name: Print the contents of the model (Directory)
        run: |
          ls model/

      - name: DVC Add
        run: |
          dvc add data/raw/sensor_data.csv data/processed/train/train.csv data/processed/test/test.csv model/random_forest_model.joblib
        
      - name: Push data to DVC remote
        run: |
          dvc push -r myremote

      - name: Configure Git
        run: |
          git config --global user.email "hammadhabib80@gmail.com"
          git config --global user.name "Hammad Habib"
  
      - name: Add, commit and push the changes
        run: |
          git pull origin main
          git add .
          git commit -m "Update data"
          git push origin main
