name: MLOPS Pipeline

on:
  push:
    branches:
      - main

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install DVC
        run: |
          pip install dvc
          dvc remote modify myremote gdrive_use_service_account true
          dvc remote modify myremote --local \
            gdrive_service_account_json_file_path mlops-secret.json
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Download the data from DVC remote
        run: |
          dvc pull

      - name: Trigger
        run: |
          date > trigger.txt

      - name: print last 100 training data
        run: |
          tail -n 100 data/processed/train/train.csv
      
      - name: print last 100 test of data
        run: |
          tail -n 100 data/processed/test/test.csv

      - name: Get New Live Data
        run: |
          dvc repro get_data

      - name: Print the newly generated data
        run: |
          cat data/processed/new_data.csv
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker Image from Docker Hub
        run: docker pull jawwadhabib/project:latest

      - name: Run Docker Container
        run: docker run -d -p 5000:5000 jawwadhabib/project:latest

      - name: Execute test_model.py
        run: python scripts/test_model.py

      - name: Run dvc pipeline
        run: |
          mse=$(cat mse_result.txt)
            if [ "$mse" '>' 0.3 ]; then
              echo "MSE exceeds threshold. Retraining..."
              dvc repro
            else
              echo "MSE is below threshold. No retraining required."
            fi
      
      # Deployment Stage      
      - name: Build and Push the Docker image
        run: |
          mse=$(cat mse_result.txt)
            if [ "$mse" '>' 0.3 ]; then
              echo "MSE exceeds threshold. Deploying..."
              docker build -t jawwadhabib/project:latest .
              docker push jawwadhabib/project:latest
            else
              echo "MSE is below threshold. No deployment required."
            fi
      # ----------------------------------------------
    
      - name: Print the contents of the model (Directory)
        if: ${{ fromJson(steps.read_mse.outputs.mse) }} > 0.25
        run: |
          ls model/

      - name: DVC Add data and Push to DVC remote
        run: |
          mse=$(cat mse_result.txt)
            if [ "$mse" '>' 0.3 ]; then
              echo "MSE exceeds threshold. Pushing updated data to remote DVC..."
              dvc add data/raw/sensor_data.csv data/processed/train/train.csv data/processed/test/test.csv model/random_forest_model.joblib
              dvc push -r myremote
            else
              echo "MSE is below threshold. No DVC push required."
            fi

      - name: Configure, Add, Commit, Push to Github
        run: |
          mse=$(cat mse_result.txt)
            if [ "$mse" '>' 0.3 ]; then
              echo "MSE exceeds threshold. Pushing Changes to Github..."
              git config --global user.email "hammadhabib80@gmail.com"
              git config --global user.name "Hammad Habib"

              git pull origin main
              git add .
              git commit -m "Update data"
              git push origin main
            else
              echo "MSE is below threshold. No Git Push required."
            fi
